### ISSUE TITLE
Webhook to auto-reload the wikis when changes are pushed

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/digitalmeX#20]
The idea is to have the webserver autoreload whenever the github repo is updated

Approach:
- define a webhook on github settings for a specific repo
- the webhook settings in github contains : 
  --url: which we will set to https://wiki.grid.tf/github/Account/Repo]
  --password: for validating the hook request

Once a new commit happens on the repo, it will make a request to the url which is already defined in lapis as a generic route.
Lapis will check the secret and validate the request, then either it will pull the repo or will forward it to a gedis actor which will do the pull using our git client

**Comment by arahmanhamdy** [comment]
https://github.com/threefoldfoundation/lapis-wiki/commit/25527bd227142f1b9eb67e5e3952b1ce16e91fe8
https://github.com/threefoldtech/digitalmeX/commit/4c7282a6d6f243d1d17b57457daac86cb7bd11ee
