### ISSUE TITLE
OpenPublish hangs in verifying links

### ISSUE THREAD

**Issue by PeterNashaat** [threefoldtech/digitalmeX#246]
![image](https://user-images.githubusercontent.com/13523434/56653311-b08d8f80-668d-11e9-9912-2fe91340dd88.png)

- and that caused issue in loading wikis
![image](https://user-images.githubusercontent.com/13523434/56653409-e9c5ff80-668d-11e9-9624-7a1a4e6b5834.png)

**Comment by abom** [comment]
Cannot reproduce, tried many times with no luck (tested it many times, and it takes too much to verify links again and again).
Are you sure these are the full logs? what's your current jumpscale log level? (see `LOGGER_LEVEL` at `/sandbox/cfg/jumpscale_config.toml`).

**Comment by despiegk** [comment]
lets disable the link checking when loading, only do when starting the tool with certain option
