### ISSUE TITLE
Lapis websites are not serving development branch

### ISSUE THREAD

**Issue by arahmanhamdy** [threefoldtech/digitalmeX#263]
Open Publish tool can serve now the lapis webiste on master branch only. We need to be able to serve the development branch too.

For example:

when referring to content from a docsite `{{{DOCSITE.DIR.PAGE}}}`
The issue is the docsite name differs form development branch and master branch

Also:
The linking of lapis files into open publish (applications,static,views) differs between development and master branches. which one to link ?

**Comment by despiegk** [comment]
will be revissited with packages in 3bot
