### ISSUE TITLE
BCDB: no way to search stored information using the index defined in the schema

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/digitalmeX#28]

**Comment by BolaNasr** [comment]
it works good
![screenshot from 2019-03-06 16-02-58](https://user-images.githubusercontent.com/10259267/53886736-5a0aba00-4029-11e9-9dfd-3620249a0e39.png)

**Comment by zaibon** [comment]
yep, so seems it was more a documentation issue then anything else. Thanks @BolaNasr
