### ISSUE TITLE
Gedis: fail to receive a schema back from a gedis actor

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/digitalmeX#30]
I have a really simple actor that has a method that should return schema:
https://github.com/threefoldtech/digitalmeX/blob/d93d5154c5ba4eac641c30614285e2cb78d676a9/packages/notary/actors/notary_actor.py#L50-L61
But when I try to call this actor, here is the error I get:
![2019-03-05_3828x788_scrot](https://user-images.githubusercontent.com/303164/53808580-ee561d80-3f52-11e9-994b-fd8348216336.png)

**Comment by BolaNasr** [comment]
it works good 
![screenshot from 2019-03-06 12-50-46](https://user-images.githubusercontent.com/10259267/53875990-7ea56880-400e-11e9-8b4e-7b4ae4843bd6.png)
