### ISSUE TITLE
notary front page

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/digitalmeX#33]
Currently the front page of the notary when going in through lapis just return a one line:
`welcome to https://github.com/threefoldtech/home/issues/135`
Which comes from https://github.com/threefoldtech/digitalmeX/blob/6a1c038ca8f467904c3d1bd5b7da69a11462cb0c/packages/notary/actors/notary_actor.py#L15-L16
and are forwarded in lapis here https://github.com/threefoldtech/digitalmeX/blob/6a1c038ca8f467904c3d1bd5b7da69a11462cb0c/packages/notary/app.moon#L7-L10

So one things is sure, what we have currently is not good enough. So or we just don't implement any index page for the web interface, or we need to decide what to put in place.

Since the notary will be reachable on the web I think it is better if we have at least a minimal home page with a decent look and feel just saying that you reach the notary.

**Comment by zaibon** [comment]
@rkhamis I was thinking we could use the same look and feel as https://threefold.io/ so we have something consistent.
I already create the html scaffolding, do you have someone that can make it beautiful ?
https://github.com/threefoldtech/digitalmeX/blob/c2bca5be19f7a7fc3974c8e983a0afaf1c8957e2/packages/notary/views/index.etlua

**Comment by rkhamis** [comment]
Sounds good.

I'll give it to the prettifying people

**Comment by BolaNasr** [comment]
Now looks good ...
we need to merge to development
![Screenshot from 2019-03-20 14-56-53](https://user-images.githubusercontent.com/10259267/54685842-7bd36900-4b20-11e9-8f8b-74d13f79c1c8.png)
Thanks @samaradel

**Comment by rkhamis** [comment]
Thanks @samaradel and @BolaNasr

**Comment by zaibon** [comment]
@BolaNasr @samaradel  Please one of you create the PR.

**Comment by samaradel** [comment]
@zaibon  
PR : https://github.com/threefoldtech/digitalmeX/pull/37
