### ISSUE TITLE
OpenWiki Verification

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/digitalmeX#42]
Check that documentation is 100% clear enough to use 
 - [x] links
 - [x] macros
 - [x] includes 

easily.

Make sure all scenarios work.

Developer docs: https://github.com/threefoldtech/jumpscaleX/tree/development/docs/tools/wiki

Child of threefoldtech/home#162

**Comment by 0xIslamTaha** [comment]
I can see that the developer docs isn't clear enough. Maybe adding **indexing** and make the content follow a specific **guideline path make** it more clear and adding more examples (full example from A to Z) will make the technical stuff more clear

**Comment by 0xIslamTaha** [comment]
**Links open 404**
![image](https://user-images.githubusercontent.com/17981089/55795350-de88a680-5ac7-11e9-973f-4e55e439c08f.png) 
![image](https://user-images.githubusercontent.com/17981089/55795681-ab92e280-5ac8-11e9-9088-57ae62c2aca0.png)


**Links open weird readmeFiles**
![image](https://user-images.githubusercontent.com/17981089/55795639-9453f500-5ac8-11e9-806e-91b5f46cd578.png)
![image](https://user-images.githubusercontent.com/17981089/55795651-9ae26c80-5ac8-11e9-9d4e-654736a7891b.png)

**Comment by 0xIslamTaha** [comment]
url link in this example load 404 page
https://github.com/threefoldtech/jumpscaleX/tree/development/docs/tools/wiki#tool-usage

**Comment by 0xIslamTaha** [comment]
verifing the new edits

**Comment by 0xIslamTaha** [comment]
@rkhamis 
I can see that if the marker isn't in the content, markdowndocs tool will load the whole content however I think it should return an empty string

**Comment by 0xIslamTaha** [comment]
**Include verification**
**Source**
```
## The whole Doc
!!!include("https://github.com/threefoldtech/jumpscaleX/tree/development/docs/tools/wiki/docsites/examples/docs/test_src.md")

## Part from doc
!!!include("https://github.com/threefoldtech/jumpscaleX/tree/development/docs/tools/wiki/docsites/examples/docs/test_src.md!A")

## Header
!!!include("https://github.com/threefoldtech/jumpscaleX/tree/development/docs/tools/wiki/docsites/examples/docs/test_src.md", header_levels_modify=2)


## From external repository
!!!include("https://github.com/abom/test_custom_md/tree/master/docs/test_src.md")


## From external repo with custom link format
!!!include("abom:test_custom_md:docs/test_src.md!B")


## From another wiki
!!!include("presentations/tech.md", docsite_name="info_foundation")
```

**Output**
```
## The whole Doc

+++
title = "hello"
+++

Hiiii how are you

## head

[b](test.md)


   This is a paragraph !!A!!
You need to include this para, para, para !!A!!

   A new para, !!B!!
This is a new para

## Part from doc

+++
title = "hello"
+++

Hiiii how are you

## head

[b](test.md)


   This is a paragraph !!A!!
You need to include this para, para, para !!A!!

   A new para, !!B!!
This is a new para

## Header

+++
title = "hello"
+++

Hiiii how are you

#### head

[b](test.md)


   This is a paragraph !!A!!
You need to include this para, para, para !!A!!

   A new para, !!B!!
This is a new para

## From external repository

+++
title = "hello"
+++

Hiiii how are you


[b] (test.md)


   This is a paragraph
You need to include this para, para, para

   A new para,
This is a new para


You can test this by doing the following:
```
...
```

## From external repo with custom link format



## From another wiki

```python
ERROR IN MACRO*** TODO: *1 ***
macro:
include
ERROR:
ERROR: Cannot find docsite with name:info_foundation

```


```

**Comment by 0xIslamTaha** [comment]
**Dots**
**Source**
```
```
!!!dot
graph graphname {
     // This attribute applies to the graph itself
     size="1,1";
     // The label attribute can be used to change the label of a node
     a [label="Foo"];
     // Here, the node shape is changed.
     b [shape=box];
     // These edges both have different line properties
     a -- b -- c [color=blue];
     b -- d [style=dotted];
     // [style=invis] hides a node.
   }
```
```
**Result**
![image](https://user-images.githubusercontent.com/17981089/55871712-86b37380-5b8b-11e9-9820-6dada849630b.png)

**Comment by rkhamis** [comment]
> I can see that if the marker isn't in the content, markdowndocs tool will load the whole content however I think it should return an empty string

Indeed, it makes more sense that the content is empty since nothing matched.

@abom I created an issue [here](https://github.com/threefoldtech/jumpscaleX/issues/331) to fix/discuss that

**Comment by 0xIslamTaha** [comment]
@abom please add a simple way to start the wiki server
