### ISSUE TITLE
Gedis javascript code generation 

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/digitalmeX#43]
Check that the javascript code generation still works as expected and can be queried from vuejs

Child of threefoldtech/home#162

**Comment by arahmanhamdy** [comment]
The javascript client is not generated anymore, we use a generic client.
Docs for using the gedis js client:
https://github.com/threefoldtech/digitalmeX/blob/development/docs/webserver/websocket-gedis.md

**Comment by john-kheir** [comment]
Verified and some changes have been done .. Commit: https://github.com/threefoldtech/digitalmeX/commit/7495abdef6833c34ed3fcbf479a4cf04593fa870
