### ISSUE TITLE
End user documentation for openwiki usage

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/digitalmeX#44]
Create very simple end user documentation for how to use:
 - [x] includes
 - [x] links
 - [x] macros
 - [x] wikis

with plenty of examples aimed at non-developers

child of threefoldtech/home#162

**Comment by rkhamis** [comment]
Send docs to @VonSub when done for clarity verification

**Comment by rkhamis** [comment]
Estimation: 1 working day

**Comment by abom** [comment]
Will skip incomplete macros like gslides (https://github.com/threefoldtech/digitalmeX/issues/53 is not done yet).

**Comment by abom** [comment]
Fixed dot macro (https://github.com/threefoldtech/jumpscaleX/commit/330db95cedcc29002a4a8102da95d0585247eca2)

Will try to clean developer docs more and add more examples, also, fixing some dead links (see https://github.com/threefoldtech/digitalmeX/issues/42#issuecomment-481182813 and https://github.com/threefoldtech/digitalmeX/issues/42#issuecomment-481207503)

**Comment by abom** [comment]
Did more clean-up and fixing links in developer docs.

**Comment by abom** [comment]
Done https://github.com/threefoldtech/digitalmeX/tree/development/docs/publishing_platform/wiki

Sent to @VonSub to review.

**Comment by abom** [comment]
@rkhamis A question regarding `how to use wikis`, what is meant by this exactly?

What i understand, if it's for end-users, he should be editing the wikis, not using technical tools or deploy his own wiki? right?

**Comment by rkhamis** [comment]
@abom perhaps it's best to have the usage of wiki usage documentation link to a more in-depth, yet step by step, documentation on 

 - how to deploy own wiki
 - how to use more advanced tooling

**Comment by abom** [comment]
Done, added a link to developer docs, it contains tool usage and reference to lapis-wiki.

**Comment by VonSub** [comment]
Looks good to me.
