### ISSUE TITLE
gdrive slides in 3bot

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/digitalmeX#45]
Expose these openresty endpoints:
 - [x] http://$IPADDR/gdrive/slide/$gpresentation_guid/$gslide_slide_guid.png
 - [ ] http://$IPADDR/gdrive/slide/$gpresentation_guid/$slidename.png 
      where the slidename is in the notes section of the slide deck as name = `<slidename>`

 The gedis actor should:
 -  get the presentation slide if older than 5 minutes.
 - Will cache the png on filesystem for 5 min.
 - save the slide to `/sandbox/var/gdrive/slides/$guid.png`

**Comment by xmonader** [comment]
caching is still remaining

**Comment by andrewayoub** [comment]
done with caching but not doable with the slide name because it's not unique enough

**Comment by AhmedHanafy725** [comment]
**Verified** on:
jumpscaleX: commit https://github.com/threefoldtech/jumpscaleX/commit/7053af180110437303848a65d79e5be3b3151ffd
digitalmeX: commit dfe044add692c546b7b2bda89f0d7447e9c660d8
lapis-wiki: commit https://github.com/threefoldfoundation/lapis-wiki/commit/d97b29380c54f93ea7da057fe4331c8b599760bf

**Comment by AhmedHanafy725** [comment]
Test can be found here [test location](https://github.com/threefoldtech/digitalmeX/tree/development/packages/gdrive/tests)
