### ISSUE TITLE
pdf gdrive docs in 3bot

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/digitalmeX#46]
The idea here is to be able to grab info from google drive docs.

Expose openresty endpoint:
 - [x] http://$IPADDR/gdrive/doc/$gdoc_guid.pdf

 The gedis actor should:
 -  get the doc if older than 5 minutes.
 - Will cache the pdf on filesystem for 5 min.
 - save the slide to `/sandbox/var/gdrive/doc/$gdoc_guid.pdf`

**Comment by xmonader** [comment]
caching is the only remaining part.

**Comment by andrewayoub** [comment]
caching done

**Comment by AhmedHanafy725** [comment]
**Verified** on:
jumpscaleX: commit https://github.com/threefoldtech/jumpscaleX/commit/7053af180110437303848a65d79e5be3b3151ffd
digitalmeX: commit dfe044add692c546b7b2bda89f0d7447e9c660d8
lapis-wiki: commit https://github.com/threefoldfoundation/lapis-wiki/commit/d97b29380c54f93ea7da057fe4331c8b599760bf

**Comment by AhmedHanafy725** [comment]
Test can be found here [test location](https://github.com/threefoldtech/digitalmeX/tree/development/packages/gdrive/tests)
