### ISSUE TITLE
gdrive spreadsheet in 3bot 

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/digitalmeX#47]
The idea here is to be able to grab info from google drive docs.

Expose openresty endpoint:
 - [x] http://$IPADDR/gdrive/spreadsheet/$gsheet_guid

 The gedis actor should:
 -  get the doc if older than 5 minutes.
 - Will cache the pdf on filesystem for 5 min.
 - save the slide to `/sandbox/var/gdrive/spreadsheet/$gsheet_guid`

**Comment by andrewayoub** [comment]
resuming investigations to find a way to convert sheets to pdf

**Comment by andrewayoub** [comment]
Gdrive api used in the gdrive client doesn't provide export methods for spread sheet but I found an endpoint which serves the spreadsheet in pdf format but it has 2 problems:
1- it requires the spread sheet to be public
2- we still need to find a way to convert the response which is a html file containing the pdf to pdf directly, I'm still investigating if there are headers to set the response type or not

example url:
https://docs.google.com/spreadsheets/d/1qRiT7Ui98QCZcYm43Kd7ZMERbbVicY-TKBe5soSmOcs//export?format=pdf&size=0&fzr=true&portrait=false&fitw=true&gridlines=false&printtitle=true&sheetnames=true&pagenum=CENTER&attachment=true

**Comment by andrewayoub** [comment]
finally reached the problem, The problem was that the sheets api doesn't provide export method but we can still use the drive api with sheets token to do that which was very strange that you use a service with another service key, it's working now and added to the endpoints

**Comment by AhmedHanafy725** [comment]
Can you update the [docs](https://github.com/threefoldtech/digitalmeX/blob/development/docs/publishing_platform/gdrive.md) with the endpoint?

**Comment by andrewayoub** [comment]
updated

**Comment by AhmedHanafy725** [comment]
**Verified on** 
digitalmeX: 5f5bdd33e1f771e3b62119984d49d7ee4b148639
jumpscaleX: https://github.com/threefoldtech/jumpscaleX/commit/060ed8f93c3d28ea2a9bc256d03b9cc359640bf1
