### ISSUE TITLE
Gallery for docsify

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/digitalmeX#49]
Choose a nice gallery component for docsify which can show pictures in a nice way.
Be creative what is possible.

**Comment by waleedhammam** [comment]
will start with docsfiy and plugins

**Comment by waleedhammam** [comment]
started working on the gallery plugin

**Comment by waleedhammam** [comment]
wrote a macro for the plugin but caught a bug after integrating with MD, currently fixing

**Comment by waleedhammam** [comment]
finished adding gallery plugin for docsify
## how to use gallery

* create md file like this:  
	```
	!!!gallery
	image1 = "https://images.pexels.com/photos/457881/pexels-photo-457881.jpeg"
	image2 = "https://geographical.co.uk/media/k2/items/cache/d0d5caef53a97465ee5797663b3cd459_XL.jpg"
	image3 = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Blue_rose-artificially_coloured.jpg/220px-Blue_rose-artificially_coloured.jpg"
	```
	- image1 = "the link of your first image"
	- .
	- .
	- and so on 

* how to use gallery
```
	url = "https://github.com/waleedhammam/gallery" # url in github that have your md file"
	gallery = j.tools.markdowndocs.load(url, name="gallery")
	gallery.write()  

	j.tools.markdowndocs.webserver()

```
open it at `yourdockerip:8080/wiki/gallery`

**Comment by waleedhammam** [comment]
## steps to make:
#### 1- making gallery macro to generate html text:
https://github.com/threefoldtech/jumpscaleX/commit/9274ff71b928648de0e8e85c9d601700c9585d63
#### 2- adding gallery js & css files:
https://github.com/threefoldtech/jumpscale_weblibs/commit/369d77d72cd0a5a0311fc56c7e272f1c28108db6
#### 3- add gallery component 
https://github.com/threefoldfoundation/lapis-wiki/commit/dc1e58bafa52e41ee9500f79fd3769d38c95bc07
