### ISSUE TITLE
Ability to not show menu

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/digitalmeX#50]
In order to embed nicely in FFP or any website, the ability to ask for a wiki page would be nice to have with the navigation menu optional

Takes parameters that accordingly would:
 - return a collapsed menu which the user can still open
 - the navigation menu is simply not visible
 - return menu

**Comment by serboctor** [comment]
I modified the `index.etlua` to parse url parameter `sidebar`, if it is set to `collapse`, the sidebar will be collapsed, if `hide`, it will be completely hidden. The default behavior is showing the sidebar.

**Comment by Dinaamagdy** [comment]
verifying by 
- start lapis server by 
``` 
cl=j.clients.open_publish.instance_name
cl.server_start()
```
- add wiki
cl.add_wiki(name,repo_url(url with docs directory), domain)
make sure that docs have _sidebar
- try in url sidebar=hide then collapse and works well both

**Comment by 0xIslamTaha** [comment]
@Dinaamagdy 
```
In [1]: cl=j.clients.open_publish.instance_name 
   ...:                                                                                                  
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/sandbox/bin/js_shell in <module>
----> 1 cl=j.clients.open_publish.instance_name

AttributeError: 'group_clients' object has no attribute 'open_publish'


```
