### ISSUE TITLE
Team plugin for docsify

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/digitalmeX#51]
Basically the javascript code we have to show our team on threefold.io

This page can then be used as an iframe inside FFP or MOBIRISE websites.

Idea is we can then embed this page in e.g. an iframe on FFP and collapse the menu so only team visible

requires #52

**Comment by abom** [comment]
The plugin is already done [here](https://github.com/threefoldtech/jumpscale_weblibs/tree/master/static/team).

Not writing some documentation.

**Comment by abom** [comment]
Done, can be found https://github.com/threefoldtech/jumpscale_weblibs/tree/master/static/team

Applied to lapis-wiki at https://github.com/threefoldfoundation/lapis-wiki/pull/6

**Comment by Dinaamagdy** [comment]
verified using latest lapis-wiki
and testing wikis repo  https://github.com/abom/test_custom_md
