### ISSUE TITLE
openwiki team macro

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/digitalmeX#52]
Will produce the required team overview with metadata in such a way it can be picked up and understood by docsify to show in the widget described #51 

Uses the information as put in our foundation wiki

The macro can use certain criteria to find the relevant team members (e.g. Project Contribution Id) and create the required structure on disk (images, ….) and content in the markdown file so the docsify team plugin can show it properly.

Example search criteria
 - One or more project contribution id’s
 - Order in which they need to be shown

**Comment by rkhamis** [comment]
member info needs to be specced, but should be in TOML

Some of the important information will be

 - Full name
 - Why do they like TF
 - Project Contribution Id(s), often more than 1
    - $projectname:$function
    - $project (e.g. TFTech, Mazraa, BetterToken, NBHDigital, TFLove, ...)
     - $type: is one of, is in relation to company or project
            - Founder
            - Ambassador
            - Contributor
            - Supporter
             - Advisor

eg: TFTech:founder, TFLove:supporter, NBHDigital:Ambassador, …

**Comment by abom** [comment]
Still working on the macro, @arahmanhamdy and @samaradel helped me to understand some confusing parts (what's the output and so on), also @VonSub will check if more info is needed.

Also, i think the directory structure need to change in [data_team](https://github.com/threefoldfoundation/data_team) repo.

**Comment by VonSub** [comment]
@abom data_team indeed is eyed to be the source of this, what changes do you propose?

**Comment by abom** [comment]
The macro should be finished https://github.com/threefoldtech/jumpscaleX/commit/23b573db3966b0eb5732f940ad267d2ce2c88a01

Will continue working on docsify plugin.

**Comment by abom** [comment]
Added a end-user docs too at https://github.com/threefoldtech/digitalmeX/blob/development/docs/publishing_platform/wiki/macro/team.md

**Comment by Dinaamagdy** [comment]
I verified the following:
- end-user docs 
- using team macro in the folowig testing repo https://github.com/abom/test_custom_md
