### ISSUE TITLE
openwiki slideshow macro

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/digitalmeX#53]
requires: https://github.com/threefoldtech/home/issues/165
revise #36 to:

```
presentationguid = gpresentation_guid
slide = intro1
slide = whyus,footer,background
slide = roadmap
```

Note the feature where we overlay the pictures (if possible otherwise skip for now !!!!)

The macro will export the pictures (use Gdrivegateway from above) to a directory and create required info in the markdown doc so the docsify plugin can pick it up.

This slideshow will be embedded in FFP, ...

**Comment by andrewayoub** [comment]
refactored the old one to use gdrive package, documentation can be found [here](https://github.com/threefoldtech/jumpscaleX/blob/development/Jumpscale/tools/markdowndocs/macros/docs/slideshow.md)

**Comment by Dinaamagdy** [comment]
## Steps 
- Start open_publish servers 
j.tools.open_publish.default.servers_start()
-  Start  default gedis server 
cl=j.clients.gedis.new("default", port=8888)
- add wiki  repo which has slideshow macro 
cl.actors.open_publish.publish_wiki("test","https://github.com/Dinaamagdy/test_custom_md","wikis.com","172.17.0.2")

## Status 
doesn't work the slideshow macro page be as shown 
![image](https://user-images.githubusercontent.com/24386802/57294420-e8ea9000-70c7-11e9-95ef-45d84296ffab.png)

**Comment by andrewayoub** [comment]
after adding gdrive actor to the base actors in open publish it's working, please verify again

**Comment by Dinaamagdy** [comment]
## Verified with the following steps :
#### configure gdrive client  :
-  drive_client = j.clients.gdrive.main 
- drive_client.credfile = "path of credential  file " 
- drive save
- do prerequisites here https://github.com/threefoldtech/jumpscaleX/blob/development/Jumpscale/tools/markdowndocs/macros/docs/slideshow.md
#### Start open_publish servers
 j.tools.open_publish.default.servers_start()                                                 

#### add wikis repo with slideshow macro 
-  cl=j.clients.gedis.new("default", port=8888)
- cl.actors.open_publish.publish_wiki("qa","https://github.com/Dinaamagdy/test_custom_md","wikis.com","172.17.0.2")  

Slideshow macro from repo 
```
!!!slideshow

presentation_1 = 1MKhc_QhRSieeVqcsNQOpkS9pu8BwmFR318gSNSYVZts
slide_1 = presentation_1[g591c9b1d5c_2_0]
```
