### ISSUE TITLE
Sonic JSX client

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/digitalmeX#54]
Sonic is an amazing rust based indexing server with minimal memory requirements, ideal for our 3bot.
There is already a python client, needs to be modified so we can use it in our gevent based JSX. 

Use kosmos config mgmt classes.

Child of threefoldtech/home#162

**Comment by rkhamis** [comment]
Estimation: 3 working days + 2 days for verification

**Comment by zaibon** [comment]
Seems the python client is built on top of asyncio. Please describe what is the plan to port it into JSX before starting to code and let me review the plan. Gevent and asyncio are not best buddies.

**Comment by xmonader** [comment]
the plan is standard python socket implementation for sonic protocol that can be patched later in gevent context 

the API usage should be mapped 1 to 1 as defined in sonic protocol with utilizing the contextmanagers
e.g

Sonic is used in two modes and you can't switch from one to another in the same session
```python
def test_ingest():
    with IngestClient("127.0.0.1", '1491', 'dmdm') as ingestcl: # j.clients.sonic.injester_get('local') as injestcl
        print(ingestcl.ping())
        print(ingestcl.protocol)
        print(ingestcl.bufsize)
        ingestcl.push("wiki", "articles", "article-1", "random text hell")
        ingestcl.push("wiki", "articles", "article-2", "for Random text heaven")
        ingestcl.push("wiki", "articles", "article-3", "another random text hello")
        ingestcl.push("wiki", "articles", "article-4", "more random text helmet")

def test_search():
    with SearchClient("127.0.0.1", '1491', 'dmdm') as querycl: # j.clients.sonic.searcher_get('local') as querycl
        print(querycl.ping())
        print(querycl.query("wiki", "articles", "hello"))
        print(querycl.query("wiki", "articles", "life"))
        print(querycl.suggest("wiki", "articles","hell"))
```

if we want to expose the search mode + ingest mode functions under the same object it can be done too. tell me what you think.

**Comment by zaibon** [comment]
> the plan is standard python socket implementation for sonic protocol that can be patched later in gevent context

Sounds good. So is the idea to fork the original repo and change network layer to use normal socket over asyncio ? I guess that would be nice to be able to propose it to the sonic maintainer then so he can add it to the list of client.

Interface in JSX also looks ok.

**Comment by xmonader** [comment]
The protocol isn't much work, I already implemented most of the protocol (with the proposed API) already https://github.com/xmonader/python-sonic/blob/master/sonic/client.py 

what is left some cleanups adding documentation and integrating the code in jsX

**Comment by xmonader** [comment]
- sonic client package is published on pypi

- JSX sonic client is [integrated](https://github.com/threefoldtech/jumpscaleX/commit/6d2507ad6bf41f7c0f6a7acfb48a9d57ecf60573)

- Handed to QA for verification

**Comment by hossnys** [comment]
verified :
```
In [2]: cl = j.clients.sonic.get("ingest_client", host="0.tcp.ngrok.io", port=15092, password="dmdm", mode="ingest") 
   ...: with cl.client as ingest_client: 
   ...:      ingest_client.push("dmdmsite", "articles", "QA_test", "demo test sonic") 

In [3]: scl = j.clients.sonic.get("search_client", host="0.tcp.ngrok.io", port=15092, password="dmdm", mode="search") 
   ...: with scl.client as search_client: 
   ...:      print(search_client.query("dmdmsite","articles", "sonic")) 
   ...:       
   ...:                                                                                                                                                                                                     
['QA_test']

In [4]: scl = j.clients.sonic.get("search_client", host="0.tcp.ngrok.io", port=15092, password="dmdm", mode="search") 
   ...: with scl.client as search_client: 
   ...:      print(search_client.suggest("dmdmsite","articles", "son")) 
   ...:                                                                                                                                                                                                      
['sonic']



```
