### ISSUE TITLE
Expand docgenerator to index content

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/digitalmeX#55]
requires #54 

When walking over the markdowns feed the info to Sonic backend using client.
Use different bucket per wiki

**Comment by rkhamis** [comment]
Estimation: 2 working days

**Comment by andrewayoub** [comment]
to use sonic for indexing you should set it to markdowndocs  tool
simple doc for the client can be found [here](https://github.com/threefoldtech/jumpscaleX/blob/development/Jumpscale/clients/sonic/README.md)
example :

```python
cl = j.clients.sonic.get("main", host="0.0.0.0", port="1491", password="XXXX") 
j.tools.markdowndocs.sonic_client_set(cl) 
j.tools.markdowndocs.webserver() 
```

to search in the loaded docs
```python
cl.query("docsites", "tokens", "repo")
```

**Comment by john-kheir** [comment]
Veriified
